export const CURRENT_LOCATION = 'CURRENT_LOCATION';
export const CURRENT_LOCATION_ERROR = 'CURRENT_LOCATION_ERROR';

export const GET_USERNAME = 'GET_USERNAME';

export const SEND_VERIFICATION = 'SEND_VERIFICATION';
export const SEND_VERIFICATION_ERROR = 'SEND_VERIFICATION_ERROR';

export const GET_USERNAMES = 'GET_USERNAMES';
export const GET_USERNAMES_ERROR = 'GET_USERNAMES_ERROR';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const CLEAR_USERNAME = 'CLEAR_USERNAME';

export const SET_CODE = 'SET_CODE';

export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const VERIFY_TOKEN_ERROR = 'VERIFY_TOKEN_ERROR';

export const VERIFY_CODE = 'VERIFY_CODE';
export const VERIFY_CODE_ERROR = 'VERIFY_CODE_ERROR';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

export const SIGNUP_NEXT = 'SIGNUP_NEXT';

export const CLEAR_SIGNUP = 'CLEAR_SIGNUP';

export const CREATE_CHURCH = 'CREATE_CHURCH';
export const CREATE_CHURCH_ERROR = 'CREATE_CHURCH_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const LOGOUT = 'LOGOUT';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const FIND_RESET = 'FIND_RESET';
export const FIND_RESET_ERROR = 'FIND_RESET_ERROR';
