export const CURRENT_LOCATION = 'CURRENT_LOCATION';
export const CURRENT_LOCATION_ERROR = 'CURRENT_LOCATION_ERROR';

export const GET_USERNAME = 'GET_USERNAME';

export const SEND_VERIFICATION = 'SEND_VERIFICATION';
export const SEND_VERIFICATION_ERROR = 'SEND_VERIFICATION_ERROR';

export const GET_USERNAMES = 'GET_USERNAMES';
export const GET_USERNAMES_ERROR = 'GET_USERNAMES_ERROR';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const CLEAR_USERNAME = 'CLEAR_USERNAME';
