export default {
  location: {},
  successMessage: '',
  errorMessage: '',
  errors: {},
  setCode: localStorage.getItem('setCode') || false,
  tokenUser: {},
  user: {},
  auth: localStorage.getItem('auth') || false,
  authToken: localStorage.getItem('authToken') || false,
  reset: false,
  tokenSent: localStorage.getItem('tokenSent') || false,
  churchCreated: localStorage.getItem('churchCreated') || false,
  activationToken: localStorage.getItem('activation_token') || null,
};
